### ISSUE TITLE
Create new logo for this edition

### ISSUE THREAD

**Issue by fernandoporazzi** [techparty/techparty#19]
The logo must follow some concepts:
- clean
- flat
- high resolution

PS.: Create multiple sizes to use in many places as needed

**Comment by marcusvmsa** [comment]
Hey guys!

I've been busy in the last days, but still I managed to work at some concepts for the new TechParty logo.

What do you guys think?

![tp-logos](https://cloud.githubusercontent.com/assets/371302/9950711/b9640802-5d93-11e5-8440-0e389013efb0.png)

**Comment by fernandoporazzi** [comment]
Wowww!

That's pretty great. We just need to chose one concept now, but this will not be a problem.

Thanks, @mamute!

**Comment by danielrohers** [comment]
Woooooow @mamute :smile:

**Comment by otondin** [comment]
Gostei do primeiro logo, porém sem a lâmpada "dentro" da xícara ficaria ainda mais legal. Gostei da fonte também. Acho que ficaria muito legal, além do posicionamento proposto, posicionar o símbolo ao lado do logotipo.

**Comment by rodrigok** [comment]
I liked the second one, TP inside a circle.

**Comment by fernandoporazzi** [comment]
I'm going to close this issue. Big thanks to @mamute who created the new logo!
