### ISSUE TITLE
Create page for Certificate of Completion

### ISSUE THREAD

**Issue by fernandoporazzi** [techparty/techparty#24]
Create a folder inside the 2016 folder and develop a brand new layout for the certificate. Maybe we could use a trending technology(React, Angular 2 or etc...).

**Comment by danielrohers** [comment]
Angular it's great idea

**Comment by fernandoporazzi** [comment]
I am really considering about using React.

**Comment by danielrohers** [comment]
Let's go :smile:

**Comment by fernandoporazzi** [comment]
I develop the client side and you can develop the server side. Ok?

**Comment by danielrohers** [comment]
Yep.. The server side is in developing [TechParty Data](https://github.com/techparty/techparty-data)

**Comment by fernandoporazzi** [comment]
I've built two wireframes

https://wireframe.cc/NPPV28

**Comment by fernandoporazzi** [comment]
This is what I got so far.

![captura de tela de 2015-12-01 23 22 01](https://cloud.githubusercontent.com/assets/2279686/11519632/ed880fd2-9882-11e5-8fc1-ebc11403834d.png)

**Comment by danielrohers** [comment]
This is beautiful.
