### ISSUE TITLE
Criar página para marcar presença em cada dia do evento.

### ISSUE THREAD

**Issue by fernandoporazzi** [techparty/techparty#25]
Atualmente, em cada dia do evento, é necessário que duas pessoas fiquem na recepção procurando o nome das pessoas e marcando presença. Penso que poderíamos automatizar essa tarefa, de forma que isso já fique salvo no banco de dados, sem necessidade de exportar um xls ou csv. 

O que acham?

**Comment by danielrohers** [comment]
@fernandoporazzi isso será feito em [techparty-data](https://github.com/techparty/techparty-data)
