### ISSUE TITLE
E-mail de contato e/ou formulário de contato no site

### ISSUE THREAD

**Issue by otondin** [techparty/techparty#27]
O que acham de ter um e-mail de contato divulgado no site ou um formulário de contato? Pode ser útil para pessoas tirar dúvidas ou até mesmo interessados em apoiar o evento entrarem em contato.

**Comment by fernandoporazzi** [comment]
Pode ser feito sim! Ainda temos algumas funcionalidades a serem desenvolvidas, e tua sugestão pode entrar junto!

**Comment by otondin** [comment]
Massa! Como estão organizando as tasks pra desenvolver as features pro site da próxima edição?

**Comment by fernandoporazzi** [comment]
Não usamos nada para organizar as tasks. Simplesmente pegamos o conteúdo atual e pensamos em um novo layout.

**Comment by otondin** [comment]
Saquei!
