### ISSUE TITLE
Menu sanduíche no layout mobile

### ISSUE THREAD

**Issue by otondin** [techparty/techparty#28]
O que acham de "contraír" os links do menu em um ícone de "sanduíche" no layout mobile ao invés do layout atual?

**Comment by fernandoporazzi** [comment]
Atualmente temos isso aqui:

![captura de tela de 2016-12-14 15-39-08](https://cloud.githubusercontent.com/assets/2279686/21193463/89164a1c-c213-11e6-9ffd-2f661f8b418e.png)

Como tu pensou em fazer?

**Comment by otondin** [comment]
Muito bonito o design do header no mobile assim! Mas não é a versão que está publicada em produção né? É a versão atual em desenvolvimento imagino.

**Comment by fernandoporazzi** [comment]
Ahhhhh! Entendi!
Todo ano fizemos um site novo para o evento. Logo o layout atual irá sair do ar e vai dar espaço para o novo, que está em desenvolvimento aqui: https://github.com/techparty/techparty/tree/master/2017

**Comment by otondin** [comment]
👍
